Chusov.lab7
MPSU/SV4DV pull request #6
Opened 2023-05-29 14:23 UTC by serge0699

2023-06-02 14:19 UTC, HepoH3 requested changes
Прогони текст через текстовый процессор, а то по существу ничего даже не предложишь, потому что постоянно отвлекаешься от содержимого на всякие опечатки

2023-06-02 14:19 UTC, HepoH3 commented on lab_07 coverage/README.md
> +- дизайн находился во всех ли возможных состояниях.
```suggestion
- дизайн находился во всех возможных состояниях.
```

2023-06-02 14:19 UTC, HepoH3 commented on lab_07 coverage/README.md
> +Стоит отметить, что к данному списку нужно относиться критически, так как **спецификация на дизайн не всегда попадает к верификатору полной, и приходится уточнять некоторые нюансы у проектировщиков**
```suggestion
Стоит отметить, что к данному списку нужно относиться критически, так как **спецификация на дизайн не всегда попадает к верификатору полной, и приходится уточнять некоторые нюансы у проектировщиков**. А наиболее частым сценарием является тот случай, когда верификатор опирается только на значения на входах и выходах, а также алгоритмы работы протоколов.
```

2023-06-02 14:19 UTC, HepoH3 commented on lab_07 coverage/README.md
> +Одним из способов подверждения перечисленных выше пунктов является сбор `функционального покрытия`.
```suggestion
Одним из способов подтверждения перечисленных выше пунктов является сбор `функционального покрытия`.
```

2023-06-02 14:19 UTC, HepoH3 commented on lab_07 coverage/README.md
> +В рамках данной лабораторной работы обучающемося **предлагается изучить конструкции функционального покрытия языка описания аппаратуры `SystemVerilog`.**
```suggestion
В рамках данной лабораторной работы обучающемуся **предлагается изучить конструкции функционального покрытия языка описания аппаратуры `SystemVerilog`.**
```

2023-06-02 14:19 UTC, HepoH3 commented on lab_07 coverage/README.md
> +Данный набор в SystemVerilog называется **моделью функционльного покрытия или `Functional Coverage Model`.**
```suggestion
Данный набор в SystemVerilog называется **моделью функционального покрытия или `Functional Coverage Model`.**
```

2023-06-02 14:19 UTC, HepoH3 commented on lab_07 coverage/README.md
> +_В данном примере определяется `covegroup` типа `cg`, а после создатся два экземпляра этого типа с именами `my_cg1` и `my_cg2`._
```suggestion
_В данном примере определяется `covegroup` типа `cg`, а после создается два экземпляра этого типа с именами `my_cg1` и `my_cg2`._
```

2023-06-02 14:19 UTC, HepoH3 commented on lab_07 coverage/README.md
> +**`coverpoint` может быть опционально маркирована меткой**, которая, если указана, будет являться именем точки покрытия. Если метка не указывается, то ПО дает точке автоматическое имя, которое являет
```suggestion
**`coverpoint` может быть опционально маркирована меткой**, которая будет являться именем точки покрытия. Если метка не указывается, то ПО дает точке автоматическое имя, которое является специфичным для каждого симулятора. Метки могут быть использованы при определении cross-покрытия.
```

2023-06-02 14:19 UTC, HepoH3 commented on lab_07 coverage/README.md
> +_В данном примере при помощи конструкции `coverpoint` определяется, что каждый фронт такового сигнала будет сохраняться информация о переменных `addr` и `wr_rd`. Также сохраняется информация о всех к
```suggestion
_В данном примере при помощи конструкции `coverpoint` определяется, что каждый фронт тактового сигнала будет сохраняться информация о переменных `addr` и `wr_rd`. Также сохраняется информация о всех комбинациях точек покрытия `с1` и `с2` при помощи конструкции `cross`. Обратите внимание, что в cross-покрытии участвуют имена точек покрытия, а не переменных._
```

2023-09-07 10:28 UTC, serge0699 commented
@HepoH3

2023-09-22 10:38 UTC, merged